### ISSUE TITLE
InventoryClickEvent

### ISSUE THREAD

**Issue by bobhenl** [ztowne13/Specialized-Crates#339]
```
[21:22:42] [Server thread/ERROR]: Could not pass event InventoryClickEvent to SpecializedCrates v2.13 - BETA 2
java.lang.IllegalArgumentException: Potion Type must not be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.16.4.jar:git-Paper-335]
	at org.bukkit.potion.PotionData.<init>(PotionData.java:23) ~[patched_1.16.4.jar:git-Paper-335]
	at me.ztowne13.customcrates.interfaces.items.ItemBuilder.reapplyPotionEffects(ItemBuilder.java:547) ~[?:?]
	at me.ztowne13.customcrates.interfaces.items.ItemBuilder.addPotionEffect(ItemBuilder.java:366) ~[?:?]
	at me.ztowne13.customcrates.interfaces.items.ItemBuilder.updateFromItem(ItemBuilder.java:117) ~[?:?]
	at me.ztowne13.customcrates.interfaces.items.ItemBuilder.<init>(ItemBuilder.java:49) ~[?:?]
	at me.ztowne13.customcrates.listeners.InventoryActionListener.onAnvilClick(InventoryActionListener.java:133) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1098.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-335]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-335]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-335]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-335]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2530) ~[patched_1.16.4.jar:git-Paper-335]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.4.jar:git-Paper-335]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.4.jar:git-Paper-335]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-335]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-335]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-335]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-335]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-335]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.4.jar:git-Paper-335]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.4.jar:git-Paper-335]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.4.jar:git-Paper-335]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1262) ~[patched_1.16.4.jar:git-Paper-335]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.4.jar:git-Paper-335]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-335]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by slooshied** [comment]
Development of this plugin has been discontinued by the original author.
